import type { CatalogCategory, CatalogProduct } from "@/entities/product/catalog";

export const catalogCategories: CatalogCategory[] = [
  {
    id: "cat-bebidas",
    slug: "bebidas",
    name: "Bebidas",
    description: "Hidratacao, sucos e bebidas para a rotina da casa.",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "cat-hortifruti",
    slug: "hortifruti",
    name: "Hortifruti",
    description: "Frutas, verduras e legumes para compras frescas.",
    sortOrder: 2,
    isActive: true,
  },
  {
    id: "cat-carnes-e-peixes",
    slug: "carnes-e-peixes",
    name: "Carnes e peixes",
    description: "Proteinas para refeicoes do dia a dia e planejamentos especiais.",
    sortOrder: 3,
    isActive: true,
  },
  {
    id: "cat-laticinios-e-frios",
    slug: "laticinios-e-frios",
    name: "Laticinios e frios",
    description: "Itens refrigerados para cafe da manha, lanches e preparo rapido.",
    sortOrder: 4,
    isActive: true,
  },
  {
    id: "cat-padaria",
    slug: "padaria",
    name: "Padaria",
    description: "Paes, torradas e itens de consumo diario da padaria.",
    sortOrder: 5,
    isActive: true,
  },
  {
    id: "cat-mercearia",
    slug: "mercearia",
    name: "Mercearia",
    description: "Base seca da casa com graos, massas, cafe e complementos.",
    sortOrder: 6,
    isActive: true,
  },
  {
    id: "cat-congelados",
    slug: "congelados",
    name: "Congelados",
    description: "Opcoes praticas para o freezer e refeicoes rapidas.",
    sortOrder: 7,
    isActive: true,
  },
  {
    id: "cat-limpeza",
    slug: "limpeza",
    name: "Limpeza",
    description: "Produtos para manutencao e higienizacao da casa.",
    sortOrder: 8,
    isActive: true,
  },
  {
    id: "cat-higiene-pessoal",
    slug: "higiene-pessoal",
    name: "Higiene pessoal",
    description: "Itens recorrentes de cuidado pessoal e reposicao domestica.",
    sortOrder: 9,
    isActive: true,
  },
  {
    id: "cat-utilidades-domesticas",
    slug: "utilidades-domesticas",
    name: "Utilidades domesticas",
    description: "Apoios para limpeza, descarte e manutencao do lar.",
    sortOrder: 10,
    isActive: true,
  },
  {
    id: "cat-itens-de-cozinha",
    slug: "itens-de-cozinha",
    name: "Itens de cozinha",
    description: "Consumiveis e apoios de preparo para a rotina da cozinha.",
    sortOrder: 11,
    isActive: true,
  },
];

export const catalogProducts: CatalogProduct[] = [
  { id: "prod-arroz-branco-5kg", slug: "arroz-branco-5kg", name: "Arroz branco 5kg", shortDescription: "Base tradicional para refeicoes do dia a dia.", categorySlug: "mercearia", unitLabel: "5kg", averagePriceCents: 2990, origin: "catalogo", isActive: true },
  { id: "prod-feijao-carioca-1kg", slug: "feijao-carioca-1kg", name: "Feijao carioca 1kg", shortDescription: "Item essencial para combinacoes classicas brasileiras.", categorySlug: "mercearia", unitLabel: "1kg", averagePriceCents: 890, origin: "catalogo", isActive: true },
  { id: "prod-macarrao-espaguete-500g", slug: "macarrao-espaguete-500g", name: "Macarrao espaguete 500g", shortDescription: "Massa pratica para almocos e jantares rapidos.", categorySlug: "mercearia", unitLabel: "500g", averagePriceCents: 549, origin: "catalogo", isActive: true },
  { id: "prod-aveia-em-flocos-500g", slug: "aveia-em-flocos-500g", name: "Aveia em flocos 500g", shortDescription: "Boa opcao para cafe da manha e lanches leves.", categorySlug: "mercearia", unitLabel: "500g", averagePriceCents: 790, origin: "ambos", isActive: true },
  { id: "prod-granola-tradicional-1kg", slug: "granola-tradicional-1kg", name: "Granola tradicional 1kg", shortDescription: "Mistura crocante para cafe da manha e snacks.", categorySlug: "mercearia", unitLabel: "1kg", averagePriceCents: 1890, origin: "ambos", isActive: true },
  { id: "prod-cafe-em-po-500g", slug: "cafe-em-po-500g", name: "Cafe em po 500g", shortDescription: "Bebida basica para a rotina da casa.", categorySlug: "mercearia", unitLabel: "500g", averagePriceCents: 1740, origin: "catalogo", isActive: true },
  { id: "prod-oleo-de-soja-900ml", slug: "oleo-de-soja-900ml", name: "Oleo de soja 900ml", shortDescription: "Oleo versatil para preparo diario.", categorySlug: "mercearia", unitLabel: "900ml", averagePriceCents: 799, origin: "catalogo", isActive: true },
  { id: "prod-azeite-de-oliva-500ml", slug: "azeite-de-oliva-500ml", name: "Azeite de oliva 500ml", shortDescription: "Gordura de apoio para saladas e finalizacao.", categorySlug: "mercearia", unitLabel: "500ml", averagePriceCents: 2990, origin: "ambos", isActive: true },
  { id: "prod-leite-integral-1l", slug: "leite-integral-1l", name: "Leite integral 1L", shortDescription: "Item base para bebidas, vitaminas e receitas.", categorySlug: "laticinios-e-frios", unitLabel: "1L", averagePriceCents: 640, origin: "ambos", isActive: true },
  { id: "prod-iogurte-natural-170g", slug: "iogurte-natural-170g", name: "Iogurte natural 170g", shortDescription: "Opcao leve para cafe da manha ou lanche.", categorySlug: "laticinios-e-frios", unitLabel: "170g", averagePriceCents: 349, origin: "ambos", isActive: true },
  { id: "prod-queijo-mucarela-200g", slug: "queijo-mucarela-200g", name: "Queijo mucarela 200g", shortDescription: "Laticinio versatil para lanches e preparos rapidos.", categorySlug: "laticinios-e-frios", unitLabel: "200g", averagePriceCents: 1190, origin: "ambos", isActive: true },
  { id: "prod-ovos-brancos-duzia", slug: "ovos-brancos-duzia", name: "Ovos brancos duzia", shortDescription: "Fonte acessivel de proteina para varias refeicoes.", categorySlug: "laticinios-e-frios", unitLabel: "duzia", averagePriceCents: 1490, origin: "ambos", isActive: true },
  { id: "prod-pao-frances-1kg", slug: "pao-frances-1kg", name: "Pao frances 1kg", shortDescription: "Item tradicional de padaria para consumo diario.", categorySlug: "padaria", unitLabel: "1kg", averagePriceCents: 1690, origin: "catalogo", isActive: true },
  { id: "prod-pao-de-forma-integral", slug: "pao-de-forma-integral", name: "Pao de forma integral", shortDescription: "Alternativa pratica para cafe da manha e lanches.", categorySlug: "padaria", unitLabel: "unidade", averagePriceCents: 990, origin: "ambos", isActive: true },
  { id: "prod-banana-prata-1kg", slug: "banana-prata-1kg", name: "Banana prata 1kg", shortDescription: "Fruta popular para lanche rapido e vitaminas.", categorySlug: "hortifruti", unitLabel: "1kg", averagePriceCents: 980, origin: "ambos", isActive: true },
  { id: "prod-maca-gala-1kg", slug: "maca-gala-1kg", name: "Maca gala 1kg", shortDescription: "Fruta pratica para consumo ao longo do dia.", categorySlug: "hortifruti", unitLabel: "1kg", averagePriceCents: 1190, origin: "ambos", isActive: true },
  { id: "prod-alface-crespa-unidade", slug: "alface-crespa-unidade", name: "Alface crespa unidade", shortDescription: "Folha base para saladas e acompanhamentos.", categorySlug: "hortifruti", unitLabel: "unidade", averagePriceCents: 399, origin: "ambos", isActive: true },
  { id: "prod-tomate-1kg", slug: "tomate-1kg", name: "Tomate 1kg", shortDescription: "Ingrediente coringa para saladas e preparos.", categorySlug: "hortifruti", unitLabel: "1kg", averagePriceCents: 849, origin: "ambos", isActive: true },
  { id: "prod-brocolis-unidade", slug: "brocolis-unidade", name: "Brocolis unidade", shortDescription: "Vegetal usado em refeicoes leves e funcionais.", categorySlug: "hortifruti", unitLabel: "unidade", averagePriceCents: 650, origin: "ambos", isActive: true },
  { id: "prod-peito-de-frango-1kg", slug: "peito-de-frango-1kg", name: "Peito de frango 1kg", shortDescription: "Proteina magra para planejamento de refeicoes.", categorySlug: "carnes-e-peixes", unitLabel: "1kg", averagePriceCents: 2150, origin: "ambos", isActive: true },
  { id: "prod-carne-moida-bovina-1kg", slug: "carne-moida-bovina-1kg", name: "Carne moida bovina 1kg", shortDescription: "Proteina versatil para almoco e jantar.", categorySlug: "carnes-e-peixes", unitLabel: "1kg", averagePriceCents: 3490, origin: "catalogo", isActive: true },
  { id: "prod-file-de-salmao-500g", slug: "file-de-salmao-500g", name: "File de salmao 500g", shortDescription: "Proteina premium para refeicoes balanceadas.", categorySlug: "carnes-e-peixes", unitLabel: "500g", averagePriceCents: 3990, origin: "ambos", isActive: true },
  { id: "prod-agua-mineral-15l", slug: "agua-mineral-15l", name: "Agua mineral 1.5L", shortDescription: "Bebida essencial para consumo diario.", categorySlug: "bebidas", unitLabel: "1.5L", averagePriceCents: 349, origin: "catalogo", isActive: true },
  { id: "prod-suco-integral-uva-1l", slug: "suco-integral-uva-1l", name: "Suco integral de uva 1L", shortDescription: "Bebida pronta para refeicoes e lanches.", categorySlug: "bebidas", unitLabel: "1L", averagePriceCents: 1290, origin: "catalogo", isActive: true },
  { id: "prod-agua-de-coco-1l", slug: "agua-de-coco-1l", name: "Agua de coco 1L", shortDescription: "Bebida leve para hidratacao e rotina ativa.", categorySlug: "bebidas", unitLabel: "1L", averagePriceCents: 1190, origin: "ambos", isActive: true },
  { id: "prod-cha-verde-1l", slug: "cha-verde-1l", name: "Cha verde 1L", shortDescription: "Bebida associada a rotinas leves e funcionais.", categorySlug: "bebidas", unitLabel: "1L", averagePriceCents: 690, origin: "ambos", isActive: true },
  { id: "prod-pizza-congelada", slug: "pizza-congelada", name: "Pizza congelada", shortDescription: "Refeicao pratica para consumo ocasional.", categorySlug: "congelados", unitLabel: "unidade", averagePriceCents: 1790, origin: "catalogo", isActive: true },
  { id: "prod-legumes-congelados-300g", slug: "legumes-congelados-300g", name: "Legumes congelados 300g", shortDescription: "Mistura pronta para agilizar refeicoes.", categorySlug: "congelados", unitLabel: "300g", averagePriceCents: 990, origin: "ambos", isActive: true },
  { id: "prod-hamburguer-vegetal-congelado", slug: "hamburguer-vegetal-congelado", name: "Hamburguer vegetal congelado", shortDescription: "Alternativa sem carne para lanches e refeicoes.", categorySlug: "congelados", unitLabel: "unidade", averagePriceCents: 1890, origin: "ambos", isActive: true },
  { id: "prod-detergente-liquido-500ml", slug: "detergente-liquido-500ml", name: "Detergente liquido 500ml", shortDescription: "Item basico para lavagem da louca.", categorySlug: "limpeza", unitLabel: "500ml", averagePriceCents: 299, origin: "catalogo", isActive: true },
  { id: "prod-sabao-em-po-16kg", slug: "sabao-em-po-16kg", name: "Sabao em po 1.6kg", shortDescription: "Produto comum para lavagem de roupas.", categorySlug: "limpeza", unitLabel: "1.6kg", averagePriceCents: 1890, origin: "catalogo", isActive: true },
  { id: "prod-papel-higienico-12-rolos", slug: "papel-higienico-12-rolos", name: "Papel higienico 12 rolos", shortDescription: "Item essencial de higiene para reposicao.", categorySlug: "higiene-pessoal", unitLabel: "12 rolos", averagePriceCents: 1890, origin: "catalogo", isActive: true },
  { id: "prod-shampoo-350ml", slug: "shampoo-350ml", name: "Shampoo 350ml", shortDescription: "Produto recorrente de cuidado pessoal.", categorySlug: "higiene-pessoal", unitLabel: "350ml", averagePriceCents: 1490, origin: "catalogo", isActive: true },
  { id: "prod-esponja-multiuso-4-unidades", slug: "esponja-multiuso-4-unidades", name: "Esponja multiuso 4 unidades", shortDescription: "Utilitario para limpeza da cozinha.", categorySlug: "utilidades-domesticas", unitLabel: "4 unidades", averagePriceCents: 549, origin: "catalogo", isActive: true },
  { id: "prod-saco-de-lixo-30l", slug: "saco-de-lixo-30l", name: "Saco de lixo 30L", shortDescription: "Consumivel domestico para descarte diario.", categorySlug: "utilidades-domesticas", unitLabel: "30L", averagePriceCents: 1290, origin: "catalogo", isActive: true },
  { id: "prod-papel-aluminio-75m", slug: "papel-aluminio-75m", name: "Papel aluminio 7.5m", shortDescription: "Item de apoio para preparo e conservacao.", categorySlug: "itens-de-cozinha", unitLabel: "7.5m", averagePriceCents: 690, origin: "catalogo", isActive: true },
  { id: "prod-filme-pvc-15m", slug: "filme-pvc-15m", name: "Filme PVC 15m", shortDescription: "Material para armazenar e proteger alimentos.", categorySlug: "itens-de-cozinha", unitLabel: "15m", averagePriceCents: 790, origin: "catalogo", isActive: true },
  { id: "prod-filtro-de-cafe-103", slug: "filtro-de-cafe-103", name: "Filtro de cafe 103", shortDescription: "Item de cozinha para preparo de cafe.", categorySlug: "itens-de-cozinha", unitLabel: "unidade", averagePriceCents: 590, origin: "catalogo", isActive: true },
];
